dependencies:
      - name: postgresql
        version: 7.7.2
        repository: https://kubernetes-charts.storage.googleapis.com/
        condition: postgresql.enabled
      - name: prometheus-pushgateway
        alias: pushgateway
        version: 1.2.6
        repository: https://kubernetes-charts.storage.googleapis.com/
      - name: rabbitmq
        version: 6.25.2
        repository: "@bitnami"
